global:
  imageRegistry: "docker.io"
  imagePullSecrets: []
  timezone: ""
networkPolicies:
  enabled: false
  type: "k3s"
image:
  longhorn:
    engine:
      registry: ""
      repository: longhornio/longhorn-engine
      tag: v1.11.0
    manager:
      registry: ""
      repository: longhornio/longhorn-manager
      tag: v1.11.0
    ui:
      registry: ""
      repository: longhornio/longhorn-ui
      tag: v1.11.0
    instanceManager:
      registry: ""
      repository: longhornio/longhorn-instance-manager
      tag: v1.11.0
    shareManager:
      registry: ""
      repository: longhornio/longhorn-share-manager
      tag: v1.11.0
    backingImageManager:
      registry: ""
      repository: longhornio/backing-image-manager
      tag: v1.11.0
    supportBundleKit:
      registry: ""
      repository: longhornio/support-bundle-kit
      tag: v0.0.79
  csi:
    attacher:
      registry: ""
      repository: longhornio/csi-attacher
      tag: v4.10.0-20251226
    provisioner:
      registry: ""
      repository: longhornio/csi-provisioner
      tag: v5.3.0-20251226
    nodeDriverRegistrar:
      registry: ""
      repository: longhornio/csi-node-driver-registrar
      tag: v2.15.0-20251226
    resizer:
      registry: ""
      repository: longhornio/csi-resizer
      tag: v2.0.0-20251226
    snapshotter:
      registry: ""
      repository: longhornio/csi-snapshotter
      tag: v8.4.0-20251226
    livenessProbe:
      registry: ""
      repository: longhornio/livenessprobe
      tag: v2.17.0-20251226
defaultSettings:
  defaultDataLocality: "best-effort"
  defaultReplicaCount: 1
  defaultDataPath: /mnt/longhorn
privateRegistry:
  createSecret: ~
  registryUrl: ~
  registryUser: ~
  registryPasswd: ~
  registrySecret: ~
longhornUI:
  replicas: 1
  # affinity:
  #   podAntiAffinity:
  #     preferredDuringSchedulingIgnoredDuringExecution:
  #       - weight: 1
  #         podAffinityTerm:
  #           labelSelector:
  #             matchExpressions:
  #               - key: app
  #                 operator: In
  #                 values:
  #                   - longhorn-ui
  #           topologyKey: kubernetes.io/hostname
ingress:
  enabled: true
  ingressClassName: "nginx"
  host: longhorn.k8s-test.neuro.tech
  tls: true
  secureBackends: false
  tlsSecret: longhorn-tls
  path: /
  pathType: ImplementationSpecific
  annotations:
    cert-manager.io/cluster-issuer: intermediate-ca-issuer
    # NGINX Ingress annotations
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10000m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    # Important for Longhorn UI functionality
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
metrics:
  serviceMonitor:
    enabled: false