apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/core-dns: "true"
spec:
  selector:
    k8s-app: kube-dns
  clusterIP: 10.32.0.10 # <--- ВАЖНО: должен быть из вашего диапазона 10.32.0.0/24
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
